#   ________      ___    ___      ________  _______   _____ ______   ___  __    ________  _____ ______   ________  ________
#  |\   __  \    |\  \  /  /|    |\   ___ \|\  ___ \ |\   _ \  _   \|\  \|\  \ |\   __  \|\   _ \  _   \|\   ____\|\   __  \
#  \ \  \|\ /_   \ \  \/  / /    \ \  \_|\ \ \   __/|\ \  \\\__\ \  \ \  \/  /|\ \  \|\  \ \  \\\__\ \  \ \  \___|\ \  \|\  \
#   \ \   __  \   \ \    / /      \ \  \ \\ \ \  \_|/_\ \  \\|__| \  \ \   ___  \ \  \\\  \ \  \\|__| \  \ \_____  \ \   __  \
#    \ \  \|\  \   \/  /  /        \ \  \_\\ \ \  \_|\ \ \  \    \ \  \ \  \\ \  \ \  \\\  \ \  \    \ \  \|____|\  \ \  \|\  \
#     \ \_______\__/  / /           \ \_______\ \_______\ \__\    \ \__\ \__\\ \__\ \_______\ \__\    \ \__\____\_\  \ \_______\
#      \|_______|\___/ /             \|_______|\|_______|\|__|     \|__|\|__| \|__|\|_______|\|__|     \|__|\_________\|_______|
#               \|___|/                                                                                    \|_________|
# Don't change this
config-version: 3

# Enable update notifications in chat for admins and console.
check-updates: true

# Used when cleaner is disabled or if item doesn't have a timer.
# Placeholders: %size%, %name%
# Note: [%countdown% placeholder will not work.]
format: "&f%name% &7(x%size%)"

# Pick up items only with the Shift key.
pickup-items-on-sneak: false

# Ignore no-pickup items, for compatibility with other plugins.
ignore-no-pickup-items: true

# Name of resource. Example: en_CA, uk_UA, de_DE, mt_MT etc.
# More: https://www.spigotmc.org/resources/divinedrop.51715/
lang: "en_CA"

messages:
  prefix: "&5&lDivineDrop &7> &f"
  display-name: "Display Name&7: &f%name%"
  no-permission: "&cYou do not have permission to run this command."
  unknown-cmd: "&cYou entered an unknown command."
  reloaded: "&aThe configuration is reloaded."

drop-cleaner:
  enabled: false
  # Placeholders: %countdown%, %size%, %name%
  format: "&c[&4%countdown%&c] &f%name% &7(x%size%)"
  # Global timer
  timer: 10
  # The timer will be added to items that are loaded along with the chunk.
  timer-for-loaded-items: true
  # Do not remove items dropped by players.
  save-player-dropped-items: false
  # Enable handling of custom countdowns.
  enable-custom-countdowns: false
  custom-countdowns:
    # Material list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    # This is the timer for all diamond swords. Such name timers will only work on objects that are not in this configuration.
    # That is, if there is already a record in the configuration with a name filter by name or emptiness, then this record will not apply to such swords.
    DIAMOND_SWORD:
      name-filter: "*"
      timer: 20
      format: "&c%name% &7(x%size%)"
    # This is the timer for an item that is not renamed.
    STICK:
      name-filter: ""
      timer: 20
    # Your timer value for items with your custom name.
    DIAMOND:
      name-filter: "SILVER"
      timer: 50
    # Such named items will be without a timer and the plugin will not delete them.
    DIAMOND:
      name-filter: "KEEP_SILVER"
      timer: -1
    # This works on all raw fish.
    RAW_FISH:
      timer: -1
