name: KartaSmartDrops
main: com.minekartastudio.kartasmartdrops.KartaSmartDrops
description: Awesome removal of items from the ground
website: https://www.spigotmc.org/members/98068/
version: ${version}
authors:
  - MinekartaStudio
api-version: 1.13
folia-supported: true
commands:
  kartasmartdrops:
    aliases: [ksd, ks]

# /ksd             | permissions: kartasmartdrops.info
# /ksd reload      | permissions: kartasmartdrops.reload
# /ksd getname     | permissions: kartasmartdrops.getname
